import React, { useEffect, useMemo, useRef, useState } from 'react'
import maplibregl from 'maplibre-gl'
import { Protocol } from 'pmtiles'
import { layers, namedFlavor } from '@protomaps/basemaps'
import { ZarrLayer } from '@carbonplan/zarr-layer'
import { makeColormap } from '@carbonplan/colormaps'

// ---------------------------------------------------------------------------
// Store configuration
// ---------------------------------------------------------------------------

const AZURE_BASE =
  'https://uwcryo.blob.core.windows.net/snowmelt/icechunk_github_actions_demo/modis_LST_multiscale_v1'

// Tile processing status GeoJSON — generated by scripts/generate_tiles_status_geojson.py.
// In development (next dev) Next.js serves public/ at the root; in production the static
// export is deployed under the GitHub Pages sub-path.
const TILES_STATUS_URL =
  process.env.NODE_ENV === 'production'
    ? '/icechunk_github_actions_demo/tiles-status.geojson'
    : '/tiles-status.geojson'

// ---------------------------------------------------------------------------
// Dataset configuration
// ---------------------------------------------------------------------------

const YEARS = [2020, 2021, 2022] as const
type Year = (typeof YEARS)[number]

// year coordinate is int64 (BigInt) — zarr-layer's indexOf(number) vs BigInt fails,
// so bypass coordinate lookup with explicit type:'index'.
const YEAR_IDX: Record<Year, number> = { 2020: 0, 2021: 1, 2022: 2 }
const yearSelector = (y: Year) => ({
  year: { selected: YEAR_IDX[y], type: 'index' as const },
})

const VARIABLE_CONFIGS = {
  avg_daytime_lst: {
    label: 'Avg Daytime LST',
    defaultColormap: 'rainbow',
    defaultClim: [-45, 45] as [number, number],
  },
  max_daytime_lst: {
    label: 'Max Daytime LST',
    defaultColormap: 'fire',
    defaultClim: [-35, 55] as [number, number],
  },
} as const

type Variable = keyof typeof VARIABLE_CONFIGS

// ---------------------------------------------------------------------------
// Colormap options (subset of @carbonplan/colormaps)
// ---------------------------------------------------------------------------

const COLORMAPS = [
  'rainbow', 'fire', 'earth', 'water', 'warm', 'cool',
  'reds', 'oranges', 'yellows', 'greens', 'teals', 'blues',
  'purples', 'pinks', 'greys', 'wind', 'heart', 'sinebow',
  'pinkgreen', 'redteal', 'orangeblue', 'yellowpurple',
]

// ---------------------------------------------------------------------------
// Basemap
// ---------------------------------------------------------------------------

// PMTiles protocol is stateful — register once per page load.
let pmtilesRegistered = false

const BASEMAP_THEME = { ...namedFlavor('black'), background: '#1b1e23', earth: '#1b1e23' }

// Protomaps assets CDN has complete Noto Sans coverage across all Unicode ranges.
const GLYPHS_URL =
  'https://protomaps.github.io/basemaps-assets/fonts/{fontstack}/{range}.pbf'

const TILES_URL =
  'pmtiles://https://carbonplan-maps.s3.us-west-2.amazonaws.com/basemaps/pmtiles/global.pmtiles'

// Satellite imagery raster layer — inserted between background and earth so that
// hiding the 'earth' fill layer reveals satellite imagery on land areas.
const ESRI_SATELLITE_SOURCE = {
  type: 'raster' as const,
  tiles: [
    'https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',
  ],
  tileSize: 256,
  maxzoom: 19,
  attribution:
    'Tiles &copy; Esri &mdash; Source: Esri, i-cubed, USDA, USGS, AEX, GeoEye, Getmapping, Aerogrid, IGN, IGP, UPR-EGP, and the GIS User Community',
}

// ---------------------------------------------------------------------------
// Styles
// ---------------------------------------------------------------------------

const BG = '#1b1e23'
const ACCENT = '#1dbd8f'
const BORDER = '#2e3138'
const TEXT = '#d0d0d0'
const DIM = '#6b7280'

// Tile status colours (match values written by get_processing_status_gdf)
const TILE_COLOR_PROCESSED = '#22c55e'
const TILE_COLOR_NODATA = '#f59e0b'
const TILE_COLOR_UNPROCESSED = '#ef4444'
const TILE_COLOR_UNKNOWN = '#94a3b8' // land tile with no status field yet

const TILE_STATUS_META: Record<string, { label: string; color: string }> = {
  processed:   { label: 'Processed',      color: TILE_COLOR_PROCESSED },
  nodata:      { label: 'No input data',  color: TILE_COLOR_NODATA },
  unprocessed: { label: 'Unprocessed',    color: TILE_COLOR_UNPROCESSED },
}

// ---------------------------------------------------------------------------
// Click info types
// ---------------------------------------------------------------------------

type TileClickInfo = {
  row: number
  col: number
  status: string
}

type ClickInfo = {
  lng: number
  lat: number
  status: 'querying' | 'done'
  valueC: number | null
}

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

export default function Map() {
  const mapContainer = useRef<HTMLDivElement>(null)
  const mapRef = useRef<maplibregl.Map | null>(null)
  const layerRef = useRef<InstanceType<typeof ZarrLayer> | null>(null)
  const markerRef = useRef<maplibregl.Marker | null>(null)

  // Map state
  const [globeProjection, setGlobeProjection] = useState(true)
  const [mapLoaded, setMapLoaded] = useState(false)
  const [isLoading, setIsLoading] = useState(false)

  // Data controls
  const [year, setYear] = useState<Year>(2020)
  const [variable, setVariable] = useState<Variable>('avg_daytime_lst')
  const [colormap, setColormap] = useState<string>(
    VARIABLE_CONFIGS.avg_daytime_lst.defaultColormap
  )
  const [clim, setClim] = useState<[number, number]>(
    VARIABLE_CONFIGS.avg_daytime_lst.defaultClim
  )
  const [climInputs, setClimInputs] = useState<[string, string]>(['-45', '45'])
  const [opacity, setOpacity] = useState(1)

  // Basemap + overlay toggles
  const [showSatellite, setShowSatellite] = useState(false)
  const [showTiles, setShowTiles] = useState(false)
  const [tilesLoaded, setTilesLoaded] = useState(false)

  // Click state
  const [clickInfo, setClickInfo] = useState<ClickInfo | null>(null)
  const [tileClickInfo, setTileClickInfo] = useState<TileClickInfo | null>(null)

  // Derived colormap array (memoized — recomputed only when colormap name changes)
  const colormapArray = useMemo(
    () => makeColormap(colormap, { format: 'hex' }),
    [colormap]
  )
  const gradient = `linear-gradient(to right, ${colormapArray.join(', ')})`

  // -- Map initialization ---------------------------------------------------
  useEffect(() => {
    if (!mapContainer.current || mapRef.current) return

    if (!pmtilesRegistered) {
      const protocol = new Protocol()
      maplibregl.addProtocol('pmtiles', protocol.tile)
      pmtilesRegistered = true
    }

    // Build protomaps layer list and insert the satellite raster layer between
    // 'background' (index 0) and 'earth' (index 1) so that hiding 'earth'
    // reveals the satellite imagery underneath it.
    const pmLayers = layers('protomaps', BASEMAP_THEME, { lang: 'en' })
    const satLayer = {
      id: 'esri-imagery',
      type: 'raster' as const,
      source: 'esri-imagery',
      layout: { visibility: 'none' as const },
    }
    const styleLayers = [pmLayers[0], satLayer, ...pmLayers.slice(1)]

    const map = new maplibregl.Map({
      container: mapContainer.current,
      style: {
        projection: { type: 'globe' },
        version: 8,
        glyphs: GLYPHS_URL,
        sources: {
          protomaps: {
            type: 'vector',
            url: TILES_URL,
            attribution:
              '<a href="https://protomaps.com">Protomaps</a>, © <a href="https://openstreetmap.org">OpenStreetMap</a>',
          },
          'esri-imagery': ESRI_SATELLITE_SOURCE,
        },
        layers: styleLayers,
      },
      center: [0, 30],
      zoom: 2,
    })

    map.on('styleimagemissing', () => {})
    mapRef.current = map
    map.on('load', () => setMapLoaded(true))

    return () => {
      map.remove()
      mapRef.current = null
      setMapLoaded(false)
    }
  }, [])

  // -- Projection toggle (no map recreation needed) -------------------------
  useEffect(() => {
    if (!mapRef.current || !mapLoaded) return
    mapRef.current.setProjection(
      globeProjection ? { type: 'globe' } : { type: 'mercator' }
    )
  }, [mapLoaded, globeProjection])

  // -- ZarrLayer (recreated when variable changes) --------------------------
  useEffect(() => {
    if (!mapLoaded || !mapRef.current) return
    const map = mapRef.current

    try {
      if (map.getLayer('zarr-layer')) map.removeLayer('zarr-layer')
    } catch {}

    const zarrLayer = new ZarrLayer({
      id: 'zarr-layer',
      source: AZURE_BASE,
      variable,
      clim,
      colormap: colormapArray,
      opacity,
      selector: yearSelector(year),
      zarrVersion: 3,
      onLoadingStateChange: ({ loading }: { loading: boolean }) =>
        setIsLoading(loading),
    })

    try {
      map.addLayer(zarrLayer, 'landuse_pedestrian')
    } catch {
      map.addLayer(zarrLayer)
    }
    layerRef.current = zarrLayer

    const clickHandler = async (event: maplibregl.MapMouseEvent) => {
      const layer = layerRef.current
      if (!layer) return

      const { lng, lat } = event.lngLat

      // Place / move persistent marker
      markerRef.current?.remove()
      markerRef.current = new maplibregl.Marker({ color: ACCENT })
        .setLngLat([lng, lat])
        .addTo(map)

      setClickInfo({ lng, lat, status: 'querying', valueC: null })

      const result = await layer.queryData({
        type: 'Point',
        coordinates: [lng, lat],
      })
      const vals = result?.[variable]
      const rawC = Array.isArray(vals) ? vals[0] : null
      setClickInfo({
        lng,
        lat,
        status: 'done',
        valueC: typeof rawC === 'number' && !isNaN(rawC) ? rawC : null,
      })
    }

    map.on('click', clickHandler)

    return () => {
      map.off('click', clickHandler)
      try {
        if (map.getLayer('zarr-layer')) map.removeLayer('zarr-layer')
      } catch {}
      layerRef.current = null
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [mapLoaded, variable])

  // -- Live updates (no layer recreation) -----------------------------------
  useEffect(() => {
    layerRef.current?.setSelector(yearSelector(year))
  }, [year])

  useEffect(() => {
    const layer = layerRef.current
    if (!layer) return
    layer.setColormap(colormapArray)
    layer.setClim(clim)
  }, [colormap, clim, colormapArray])

  useEffect(() => {
    layerRef.current?.setOpacity(opacity)
  }, [opacity])

  // -- Processing tiles overlay (loaded once after map is ready) ------------
  useEffect(() => {
    if (!mapLoaded || !mapRef.current) return
    const map = mapRef.current

    map.addSource('tiles-status', { type: 'geojson', data: TILES_STATUS_URL })

    // Add fill and outline layers above zarr data but below text labels.
    // 'address_label' is the first symbol layer in the protomaps style.
    map.addLayer(
      {
        id: 'tiles-fill',
        type: 'fill',
        source: 'tiles-status',
        filter: ['==', ['get', 'land'], true],
        paint: {
          'fill-color': [
            'case',
            ['==', ['get', 'status'], 'processed'], TILE_COLOR_PROCESSED,
            ['==', ['get', 'status'], 'nodata'], TILE_COLOR_NODATA,
            ['==', ['get', 'status'], 'unprocessed'], TILE_COLOR_UNPROCESSED,
            TILE_COLOR_UNKNOWN,
          ],
          'fill-opacity': 0.25,
        },
        layout: { visibility: 'none' },
      } as maplibregl.FillLayerSpecification,
      'address_label'
    )

    map.addLayer(
      {
        id: 'tiles-outline',
        type: 'line',
        source: 'tiles-status',
        filter: ['==', ['get', 'land'], true],
        paint: { 'line-color': '#64748b', 'line-width': 0.5 },
        layout: { visibility: 'none' },
      } as maplibregl.LineLayerSpecification,
      'address_label'
    )

    const tileClickHandler = (e: maplibregl.MapLayerMouseEvent) => {
      const props = e.features?.[0]?.properties
      if (!props) return
      setTileClickInfo({
        row: props.row,
        col: props.col,
        status: props.status ?? 'unknown',
      })
    }
    const cursorOn = () => { map.getCanvas().style.cursor = 'pointer' }
    const cursorOff = () => { map.getCanvas().style.cursor = '' }

    map.on('click', 'tiles-fill', tileClickHandler)
    map.on('mouseenter', 'tiles-fill', cursorOn)
    map.on('mouseleave', 'tiles-fill', cursorOff)

    setTilesLoaded(true)

    return () => {
      map.off('click', 'tiles-fill', tileClickHandler)
      map.off('mouseenter', 'tiles-fill', cursorOn)
      map.off('mouseleave', 'tiles-fill', cursorOff)
      try { map.removeLayer('tiles-fill') } catch {}
      try { map.removeLayer('tiles-outline') } catch {}
      try { map.removeSource('tiles-status') } catch {}
      setTilesLoaded(false)
    }
  }, [mapLoaded])

  // -- Satellite toggle ------------------------------------------------------
  useEffect(() => {
    if (!mapRef.current || !mapLoaded) return
    const map = mapRef.current
    map.setLayoutProperty('esri-imagery', 'visibility', showSatellite ? 'visible' : 'none')
    // Hide the dark 'earth' fill so satellite imagery shows through on land.
    map.setLayoutProperty('earth', 'visibility', showSatellite ? 'none' : 'visible')
  }, [mapLoaded, showSatellite])

  // -- Tiles overlay toggle -------------------------------------------------
  useEffect(() => {
    if (!mapRef.current || !tilesLoaded) return
    const v = showTiles ? 'visible' : 'none'
    mapRef.current.setLayoutProperty('tiles-fill', 'visibility', v)
    mapRef.current.setLayoutProperty('tiles-outline', 'visibility', v)
    if (!showTiles) setTileClickInfo(null)
  }, [tilesLoaded, showTiles])

  // -- Variable change: reset colormap + clim to per-variable defaults ------
  const handleVariableChange = (v: Variable) => {
    const cfg = VARIABLE_CONFIGS[v]
    setVariable(v)
    setColormap(cfg.defaultColormap)
    setClim(cfg.defaultClim)
    setClickInfo(null)
    markerRef.current?.remove()
    markerRef.current = null
  }

  // -- Clim text inputs -----------------------------------------------------
  const commitClimInput = (index: 0 | 1, value?: string) => {
    const val = parseFloat(value ?? climInputs[index])
    if (Number.isFinite(val)) {
      setClim((prev) => (index === 0 ? [val, prev[1]] : [prev[0], val]))
    } else {
      setClimInputs([String(clim[0]), String(clim[1])])
    }
  }

  const handleClimInputChange = (index: 0 | 1, raw: string) => {
    setClimInputs((prev) => (index === 0 ? [raw, prev[1]] : [prev[0], raw]))
  }

  // Keep text inputs in sync when clim changes externally (variable reset)
  useEffect(() => {
    setClimInputs([String(clim[0]), String(clim[1])])
  }, [clim])

  // -- Render ---------------------------------------------------------------
  const climMid = (clim[0] + clim[1]) / 2

  return (
    <div
      style={{
        position: 'relative',
        width: '100vw',
        height: '100vh',
        background: BG,
        overflow: 'hidden',
        fontFamily: 'system-ui, -apple-system, sans-serif',
      }}
    >
      {/* Map canvas */}
      <div ref={mapContainer} style={{ position: 'absolute', inset: 0 }} />

      {/* Sidebar */}
      <div
        style={{
          position: 'absolute',
          top: 0,
          left: 0,
          bottom: 0,
          width: 284,
          background: 'rgba(22,25,30,0.96)',
          borderRight: `1px solid ${BORDER}`,
          backdropFilter: 'blur(6px)',
          display: 'flex',
          flexDirection: 'column',
          color: TEXT,
          fontSize: 13,
          zIndex: 10,
          overflowY: 'auto',
        }}
      >
        {/* Header */}
        <div
          style={{
            padding: '20px 18px 14px',
            borderBottom: `1px solid ${BORDER}`,
            flexShrink: 0,
          }}
        >
          <div style={{ fontSize: 17, fontWeight: 700, color: '#fff', marginBottom: 2 }}>
            MODIS LST
          </div>
          <div style={{ fontSize: 11, color: DIM, lineHeight: 1.4 }}>
            MODIS MYD11C3 · Land Surface Temperature
            <br />
            0.01° (~1 km) · Annual mean &amp; max
          </div>
        </div>

        {/* Controls */}
        <div
          style={{
            flex: 1,
            padding: '16px 18px',
            display: 'flex',
            flexDirection: 'column',
            gap: 20,
          }}
        >
          {/* Variable */}
          <Section label="Variable">
            {(Object.keys(VARIABLE_CONFIGS) as Variable[]).map((v) => (
              <button
                key={v}
                onClick={() => handleVariableChange(v)}
                style={chipStyle(v === variable)}
              >
                {VARIABLE_CONFIGS[v].label}
              </button>
            ))}
          </Section>

          {/* Year */}
          <Section label="Year">
            <div style={{ display: 'flex', gap: 6 }}>
              {YEARS.map((y) => (
                <button
                  key={y}
                  onClick={() => setYear(y)}
                  style={{ ...chipStyle(y === year), flex: 1, textAlign: 'center' }}
                >
                  {y}
                </button>
              ))}
            </div>
          </Section>

          {/* Colormap */}
          <Section label="Colormap">
            <select
              value={colormap}
              onChange={(e) => setColormap(e.target.value)}
              style={{
                width: '100%',
                padding: '6px 8px',
                borderRadius: 4,
                background: '#1e2128',
                color: TEXT,
                border: `1px solid ${BORDER}`,
                fontSize: 13,
                cursor: 'pointer',
              }}
            >
              {COLORMAPS.map((c) => (
                <option key={c} value={c}>
                  {c}
                </option>
              ))}
            </select>
            <div style={{ height: 10, borderRadius: 3, marginTop: 8, background: gradient }} />
            <div
              style={{
                display: 'flex',
                justifyContent: 'space-between',
                marginTop: 3,
                fontSize: 11,
                color: DIM,
              }}
            >
              <span>{clim[0]}°</span>
              <span>{climMid.toFixed(0)}°</span>
              <span>{clim[1]}°</span>
            </div>
          </Section>

          {/* Range */}
          <Section label="Range (°C)">
            <div style={{ display: 'flex', gap: 8, alignItems: 'center' }}>
              <input
                type="number"
                value={climInputs[0]}
                onChange={(e) => handleClimInputChange(0, e.target.value)}
                onBlur={() => commitClimInput(0)}
                onKeyDown={(e) => {
                  if (e.key === 'Enter') commitClimInput(0)
                }}
                style={numInputStyle}
              />
              <div style={{ flex: 1, height: 6, borderRadius: 3, background: gradient }} />
              <input
                type="number"
                value={climInputs[1]}
                onChange={(e) => handleClimInputChange(1, e.target.value)}
                onBlur={() => commitClimInput(1)}
                onKeyDown={(e) => {
                  if (e.key === 'Enter') commitClimInput(1)
                }}
                style={numInputStyle}
              />
            </div>
          </Section>

          {/* Opacity */}
          <Section label={`Opacity — ${Math.round(opacity * 100)}%`}>
            <input
              type="range"
              min={0}
              max={1}
              step={0.01}
              value={opacity}
              onChange={(e) => setOpacity(Number(e.target.value))}
              style={{ width: '100%', accentColor: ACCENT, cursor: 'pointer' }}
            />
          </Section>

          {/* Inspect — always visible; shows placeholder before first click */}
          <Section label="Inspect">
            {clickInfo ? (
              <div
                style={{
                  padding: '12px 14px',
                  background: '#1e2128',
                  borderRadius: 6,
                  border: `1px solid ${BORDER}`,
                }}
              >
                <div
                  style={{
                    display: 'flex',
                    justifyContent: 'space-between',
                    alignItems: 'center',
                    marginBottom: 10,
                  }}
                >
                  <div style={{ fontSize: 11, color: DIM }}>Selected point</div>
                  <button
                    onClick={() => {
                      setClickInfo(null)
                      markerRef.current?.remove()
                      markerRef.current = null
                    }}
                    style={{
                      background: 'none',
                      border: 'none',
                      color: DIM,
                      cursor: 'pointer',
                      fontSize: 18,
                      lineHeight: 1,
                      padding: 0,
                    }}
                    aria-label="Clear marker"
                  >
                    ×
                  </button>
                </div>
                <div style={{ display: 'flex', flexDirection: 'column', gap: 4, marginBottom: 12 }}>
                  <CoordRow label="Lat" value={`${clickInfo.lat.toFixed(4)}°`} />
                  <CoordRow label="Lon" value={`${clickInfo.lng.toFixed(4)}°`} />
                </div>
                <div style={{ fontSize: 22, fontWeight: 700, color: '#fff', lineHeight: 1 }}>
                  {clickInfo.status === 'querying'
                    ? 'Querying…'
                    : clickInfo.valueC !== null
                    ? `${clickInfo.valueC.toFixed(1)} °C`
                    : 'No data'}
                </div>
              </div>
            ) : (
              <div style={{ fontSize: 12, color: DIM, fontStyle: 'italic' }}>
                Select a point to inspect its value.
              </div>
            )}
          </Section>

          {/* Basemap */}
          <Section label="Basemap">
            <div style={{ display: 'flex', gap: 6 }}>
              {[
                { label: 'Dark', value: false },
                { label: 'Satellite', value: true },
              ].map((opt) => (
                <button
                  key={String(opt.value)}
                  onClick={() => setShowSatellite(opt.value)}
                  style={{
                    ...chipStyle(showSatellite === opt.value),
                    flex: 1,
                    textAlign: 'center',
                  }}
                >
                  {opt.label}
                </button>
              ))}
            </div>
          </Section>

          {/* Projection */}
          <Section label="Projection">
            <div style={{ display: 'flex', gap: 6 }}>
              {[
                { label: 'Globe', value: true },
                { label: 'Mercator', value: false },
              ].map((opt) => (
                <button
                  key={String(opt.value)}
                  onClick={() => setGlobeProjection(opt.value)}
                  style={{
                    ...chipStyle(globeProjection === opt.value),
                    flex: 1,
                    textAlign: 'center',
                  }}
                >
                  {opt.label}
                </button>
              ))}
            </div>
          </Section>

          {/* Overlays */}
          <Section label="Overlays">
            <button
              onClick={() => setShowTiles((p) => !p)}
              style={chipStyle(showTiles)}
            >
              Processing tiles
            </button>
            {showTiles && (
              <div
                style={{
                  display: 'flex',
                  flexDirection: 'column',
                  gap: 4,
                  marginTop: 8,
                  padding: '8px 10px',
                  background: '#1e2128',
                  borderRadius: 4,
                  border: `1px solid ${BORDER}`,
                }}
              >
                {[
                  { color: TILE_COLOR_PROCESSED, label: 'Processed' },
                  { color: TILE_COLOR_NODATA, label: 'No input data' },
                  { color: TILE_COLOR_UNPROCESSED, label: 'Unprocessed' },
                  { color: TILE_COLOR_UNKNOWN, label: 'Unknown' },
                ].map(({ color, label }) => (
                  <div key={label} style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                    <div
                      style={{
                        width: 12,
                        height: 12,
                        borderRadius: 2,
                        background: color,
                        flexShrink: 0,
                      }}
                    />
                    <span style={{ fontSize: 11, color: DIM }}>{label}</span>
                  </div>
                ))}
              </div>
            )}
            {showTiles && tileClickInfo ? (
              <div
                style={{
                  marginTop: 8,
                  padding: '12px 14px',
                  background: '#1e2128',
                  borderRadius: 6,
                  border: `1px solid ${BORDER}`,
                }}
              >
                <div
                  style={{
                    display: 'flex',
                    justifyContent: 'space-between',
                    alignItems: 'center',
                    marginBottom: 10,
                  }}
                >
                  <div style={{ fontSize: 11, color: DIM }}>Selected tile</div>
                  <button
                    onClick={() => setTileClickInfo(null)}
                    style={{
                      background: 'none',
                      border: 'none',
                      color: DIM,
                      cursor: 'pointer',
                      fontSize: 18,
                      lineHeight: 1,
                      padding: 0,
                    }}
                    aria-label="Clear tile selection"
                  >
                    ×
                  </button>
                </div>
                <div style={{ display: 'flex', flexDirection: 'column', gap: 4, marginBottom: 10 }}>
                  <CoordRow label="Row" value={String(tileClickInfo.row)} />
                  <CoordRow label="Col" value={String(tileClickInfo.col)} />
                </div>
                <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                  <div
                    style={{
                      width: 10,
                      height: 10,
                      borderRadius: 2,
                      background: TILE_STATUS_META[tileClickInfo.status]?.color ?? TILE_COLOR_UNKNOWN,
                      flexShrink: 0,
                    }}
                  />
                  <span style={{ fontSize: 15, fontWeight: 700, color: '#fff' }}>
                    {TILE_STATUS_META[tileClickInfo.status]?.label ?? tileClickInfo.status}
                  </span>
                </div>
              </div>
            ) : showTiles ? (
              <div style={{ fontSize: 12, color: DIM, fontStyle: 'italic', marginTop: 8 }}>
                Click a tile to inspect its status.
              </div>
            ) : null}
          </Section>

          {/* Status messages */}
          {isLoading && <StatusRow>Loading chunks…</StatusRow>}
        </div>

        {/* Footer */}
        <div
          style={{
            padding: '10px 18px',
            borderTop: `1px solid ${BORDER}`,
            fontSize: 10,
            color: '#444',
            lineHeight: 1.5,
            flexShrink: 0,
          }}
        >
          Data: NASA MODIS MYD11C3 v6.1
          <br />
          Powered by{' '}
          <a href="https://github.com/earth-mover/icechunk" style={{ color: '#555' }}>
            Icechunk
          </a>{' '}
          +{' '}
          <a href="https://github.com/carbonplan/zarr-layer" style={{ color: '#555' }}>
            zarr-layer
          </a>
        </div>
      </div>
    </div>
  )
}

// ---------------------------------------------------------------------------
// Small helpers
// ---------------------------------------------------------------------------

function Section({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div>
      <div
        style={{
          fontSize: 10,
          color: DIM,
          textTransform: 'uppercase',
          letterSpacing: '0.08em',
          fontWeight: 600,
          marginBottom: 8,
        }}
      >
        {label}
      </div>
      {children}
    </div>
  )
}

function CoordRow({ label, value }: { label: string; value: string }) {
  return (
    <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: 12 }}>
      <span style={{ color: DIM }}>{label}</span>
      <span style={{ color: TEXT, fontWeight: 600, fontVariantNumeric: 'tabular-nums' }}>
        {value}
      </span>
    </div>
  )
}

function StatusRow({ children }: { children: React.ReactNode }) {
  return (
    <div style={{ fontSize: 12, color: DIM, display: 'flex', alignItems: 'center', gap: 8 }}>
      <span
        style={{
          display: 'inline-block',
          width: 8,
          height: 8,
          borderRadius: '50%',
          background: ACCENT,
        }}
      />
      {children}
    </div>
  )
}

const chipStyle = (active: boolean): React.CSSProperties => ({
  display: 'block',
  width: '100%',
  textAlign: 'left',
  padding: '7px 10px',
  marginBottom: 5,
  cursor: 'pointer',
  background: active ? ACCENT : 'transparent',
  color: active ? '#000' : TEXT,
  border: `1px solid ${active ? ACCENT : BORDER}`,
  borderRadius: 4,
  fontSize: 12,
  fontWeight: active ? 700 : 400,
})

const numInputStyle: React.CSSProperties = {
  width: 58,
  padding: '5px 7px',
  borderRadius: 4,
  background: '#1e2128',
  color: TEXT,
  border: `1px solid ${BORDER}`,
  fontSize: 13,
}
